baseurl = "https://blog.jkkitakita.dev"
languageCode = "ja"
title = "jkkitakita"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/jkkitakita\">Jun Kitamura</a> 2020"
disqusShortname = "jkkitakita"
googleAnalytics = "G-HL54XBN7N3"
Paginate = 5 # Number of posts per page
enableRobotsTXT = true

[params.rss] # Adding this tag enables RSS feed
includeContent = true # Includes whole content in rss
authorName = "Jun Kitamura" # Author full name
authorEmail = "jkkitakita@gmail.com" # Author email

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article
codeCopy = true # Add copy button above code blocks

[params.features]
disqusOnDemand = true  # Load Disqus comments on click


[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "jkkitakita" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]
twitter = "jkkitakita"
github = "jkkitakita"
email = "jkkitakita@gmail.com"
linkedin = "jkkitakita"
facebook = "jkkitakita"
instagram = "jkkitakita"
codepen = ""
rss = "index.xml" # Add this to show RSS button in social.

[params.social.config]
platforms = ["github","facebook","twitter","instagram","email","codepen","linkedin"]

[params.matomoAnalytics]
siteID = 1
rootURL = "//matomo.example.com/"

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true